version: '2'

networks:
   backend:
       
volumes:
   datavolume:

services:
   restheart:
      image: softinstigate/restheart
      depends_on:
       - mongodb
      networks:
       - backend
      ports:
       - "10080:80"
       - "10443:443"
      volumes:
        - "./restheart/config/:/opt/restheart/etc:ro"

   mongodb:      
      image: mongo:3.5
      volumes:
       - datavolume:/data/db
      networks:
       - backend
      ports:
       - "4456:27017"